export const exchangeListData = [
  {
    currencyCount: 515,
    exchBalanceEnabledV2: true,
    exchCode: 'BINA',
    exchHasWhitelisting: false,
    exchId: 70,
    exchJson: null,
    exchMarketsInverted: false,
    exchName: 'Binance',
    exchTradeEnabledV2: true,
    exchUrl: 'https://binance.com',
    exchVolume1: 20377.3,
    exchVolume24: 657085,
    favoritesScore: 740615,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 29391,
    marketCount: 2144,
    quoteCount: 32,
    slug: 'binance',
    trafficRank: 488,
    trafficRank90dChange: -93
  },
  {
    currencyCount: 543,
    exchBalanceEnabledV2: true,
    exchCode: 'BTRX',
    exchHasWhitelisting: true,
    exchId: 15,
    exchJson: null,
    exchMarketsInverted: false,
    exchName: 'Bittrex',
    exchTradeEnabledV2: true,
    exchUrl: 'https://bittrex.com/',
    exchVolume1: 49.6478,
    exchVolume24: 654.323,
    favoritesScore: 522530,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 18363,
    marketCount: 1004,
    quoteCount: 6,
    slug: 'bittrex',
    trafficRank: 45575,
    trafficRank90dChange: 1099
  },
  {
    currencyCount: 238,
    exchBalanceEnabledV2: true,
    exchCode: 'GDAX',
    exchHasWhitelisting: false,
    exchId: 62,
    exchJson: null,
    exchMarketsInverted: false,
    exchName: 'Coinbase Pro',
    exchTradeEnabledV2: true,
    exchUrl: 'https://pro.coinbase.com',
    exchVolume1: 3410.29,
    exchVolume24: 62541.7,
    favoritesScore: 88993,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 6553,
    marketCount: 552,
    quoteCount: 8,
    slug: 'coinbase-pro',
    trafficRank: 1723,
    trafficRank90dChange: 353
  },
  {
    currencyCount: 221,
    exchBalanceEnabledV2: true,
    exchCode: 'KRKN',
    exchHasWhitelisting: false,
    exchId: 11,
    exchJson: null,
    exchMarketsInverted: false,
    exchName: 'Kraken',
    exchTradeEnabledV2: true,
    exchUrl: 'https://www.kraken.com/',
    exchVolume1: 1160.39,
    exchVolume24: 24315.7,
    favoritesScore: 105756,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 6281,
    marketCount: 668,
    quoteCount: 14,
    slug: 'kraken',
    trafficRank: 10736,
    trafficRank90dChange: 2504
  },
  {
    currencyCount: 808,
    exchBalanceEnabledV2: true,
    exchCode: 'KUCN',
    exchHasWhitelisting: true,
    exchId: 76,
    exchJson: null,
    exchMarketsInverted: false,
    exchName: 'Kucoin',
    exchTradeEnabledV2: true,
    exchUrl: 'https://kucoin.com',
    exchVolume1: 1071.74,
    exchVolume24: 22721.9,
    favoritesScore: 57089,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 6118,
    marketCount: 1295,
    quoteCount: 11,
    slug: 'kucoin',
    trafficRank: 8597,
    trafficRank90dChange: 2199
  },
  {
    currencyCount: 392,
    exchBalanceEnabledV2: true,
    exchCode: 'PLNX',
    exchHasWhitelisting: false,
    exchId: 13,
    exchJson: null,
    exchMarketsInverted: true,
    exchName: 'Poloniex',
    exchTradeEnabledV2: true,
    exchUrl: 'https://www.poloniex.com/',
    exchVolume1: 112.084,
    exchVolume24: 2760.27,
    favoritesScore: 144037,
    hasFuturesTrading: false,
    hasSpotTrading: true,
    heatIndex: 3517,
    marketCount: 613,
    quoteCount: 15,
    slug: 'poloniex',
    trafficRank: 32776,
    trafficRank90dChange: -3327
  }
];

export const currencyListData = [
  {
    availableSupply: '122373866.2178',
    currCode: 'ETH',
    currId: 6579,
    currName: 'Ethereum',
    description:
      "ETH is a cryptocurrency. It is scarce digital money that you can use on the internet – similar to Bitcoin. If you’re new to crypto, here's how ETH is different from traditional money.\n\nETH's valuable in different ways to different people.\n\nFor users of Ethereum, ETH is valuable because it lets you pay transaction fees.\n\nOthers see it as a digital store of value because the creation of new ETH slows down over time.\n\nMore recently, ETH has become valuable to users of financial apps on Ethereum. That's because you can use ETH as collateral for crypto loans, or as a payment system.\n\nOf course, many also see it as an investment, similar to Bitcoin or other cryptocurrencies.",
    descriptionSource: 'https://ethereum.org/en/eth/',
    favoritesScore: 163628,
    isFiat: false,
    marketCap: '{"usd":192277597651.5185}',
    marketCapUsd: 192277597651.5185,
    miningAlgorithm: 'Dagger Hashimoto',
    miningBlockTime: 'https://en.bitcoin.it/wiki/Controlled_supply',
    miningConfirmationTime: '10 minutes',
    miningConfirmations: '',
    miningTotalCirculation: '?',
    miningType: 'Proof of Stake ',
    slug: 'eth-ethereum',
    urlWebsite: 'https://ethereum.org/en/',
    walletTrackable: true
  },
  {
    availableSupply: '19278806',
    currCode: 'BTC',
    currId: 1,
    currName: 'Bitcoin',
    description:
      'Bitcoin (BTC) is the gold standard against which all other cryptocurrencies are measured. No other altcoin can match its community, user base or reputation. It is a decentralized digital currency that is based on cryptography. As such, it can operate without the need of a central authority like a central bank or a company. It is unlike government-issued or fiat currencies such as US Dollars or Euro in which they are controlled by the country’s central bank. The decentralized nature allows it to operate on a peer-to-peer network whereby users are able to send funds to each other without going through intermediaries.',
    descriptionSource: 'https://www.coingecko.com/en/coins/bitcoin',
    favoritesScore: 255304,
    isFiat: false,
    marketCap: '{"usd":443238678782.18695}',
    marketCapUsd: 443238678782.18695,
    miningAlgorithm: 'SHA-256',
    miningBlockTime: 'https://en.bitcoin.it/wiki/Controlled_supply',
    miningConfirmationTime: '10 minutes',
    miningConfirmations: '6',
    miningTotalCirculation: '21000000',
    miningType: 'Proof of Work',
    slug: 'btc-bitcoin',
    urlWebsite: 'https://bitcoin.org/en/',
    walletTrackable: true
  },
  {
    availableSupply: '0',
    currCode: 'WETH',
    currId: 55351,
    currName: 'Wrapped Ethereum',
    description: '',
    descriptionSource: '',
    favoritesScore: 161,
    isFiat: false,
    marketCap: '{"usd":0}',
    marketCapUsd: 0,
    miningAlgorithm: '',
    miningBlockTime: '',
    miningConfirmationTime: '',
    miningConfirmations: '',
    miningTotalCirculation: '?',
    miningType: '',
    slug: 'weth-wrapped-ethereum',
    urlWebsite: '',
    walletTrackable: false
  }
];
